export default {
    itemsList: document.querySelector('.list__items'),
    addName: document.querySelector('.add__name'),
    addValue: document.querySelector('.add__value'),
    submitButton: document.querySelector('.submit__button'),
    clearButton: document.querySelector('.clear__all-button'),
    removeItem: document.querySelector('.item__remove'),
    sortByCalories: document.querySelector('.list__sort-btn'),
    search: document.querySelector('.list__filter-by'),
    clearAll: document.querySelector('.list__clear'),
    total: document.querySelector('.info__total-value'),
    goal: document.querySelector('.info__goal-span'),
    edit: document.querySelector('.info__edit'),
    chartValue: document.querySelector('.chart__value'),
    chartGoal: document.querySelector('.chart__goal'),
    bar: document.querySelector('.bar'),
}